### ISSUE TITLE
Unable to run, pinecone issue?

### ISSUE THREAD

**Issue by joshfryart** [seanpixel/Teenage-AGI#1]
I've tried renaming things without capitals, but nothing works?

`PS C:\Users\joshu\Documents\_aipython\LLMS\teenage-agi> python main.py
Traceback (most recent call last):
  File "C:\Users\joshu\Documents\_aipython\LLMS\teenage-agi\main.py", line 7, in <module>
    agent.createIndex()
  File "C:\Users\joshu\Documents\_aipython\LLMS\teenage-agi\agent.py", line 81, in createIndex
    pinecone.create_index(
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\manage.py", line 118, in create_index
    api_instance.create_index(create_request=CreateRequest(
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api\index_operations_api.py", line 370, in __create_index
    return self.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pinecone\core\client\rest.py", line 230, in request
    raise ApiException(http_resp=r)
pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Wed, 12 Apr 2023 02:36:38 GMT', 'x-envoy-upstream-service-time': '0', 'content-length': '123', 'server': 'envoy'})
HTTP response body: Index name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character
`

**Comment by seanpixel** [comment]
it seems like the pinecone vector index is the problem, did you change the index by any chance?

**Comment by Marcus-Arcadius** [comment]
same issue

**Comment by seanpixel** [comment]
try running it in python3.8? i'm not sure how the index can be set to anything other than "thought-{id}"

**Comment by joshfryart** [comment]
> it seems like the pinecone vector index is the problem, did you change the index by any chance?

I created a new account, just to be sure and it had the same issue. I then tried to download and install everything on python 3.8 (windows 11) and apparently it can't let me install pip onto 3.8 environment for some reason, let alone the requirements.txt or openai?? fun. 🗡️ 

Now, though, with the new pinecone.io index (I inputted the size of the index the same as in agent.py, same for cosine and P1.). Now, when I use python 3.10; and do 

`python agent.py`

it just doesn't do anything, and returns me to the command line for more typing. - technically no errors, so that's an improvement?

I think I may be bad at PCs.

**Comment by etherealheim** [comment]
Having the same issue. you can try python3.8 main.py, or whatever version you have installed. I don’t think tho it’s a python version issue.

**Comment by Marcus-Arcadius** [comment]
> Having the same issue. you can try python3.8 main.py, or whatever version you have installed. I don’t think tho it’s a python version issue.

still doesn't work same error like last 

pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Wed, 12 Apr 2023 10:34:55 GMT', 'x-envoy-upstream-service-time': '0', 'content-length': '123', 'server': 'envoy'})
HTTP response body: Index name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character

**Comment by danwils33** [comment]
i'm on a windows and we had this issue in another project, we just renamed the index. i'm having trouble locating the pinecone index value here, though. what is the default name for it?

**Comment by joshfryart** [comment]
I also couldnt find the name of the index. In the files. I tried
table_name, none and None.

**Comment by danwils33** [comment]
that fixed it for me

**Comment by mikekelly** [comment]
Yo! This can be closed as it was fixed with this PR that's now been merged: https://github.com/seanpixel/Teenage-AGI/pull/5

**Comment by Marcus-Arcadius** [comment]
new update fixed for me as well
