### ISSUE TITLE
Can't run the agent; PINECONE API issue

### ISSUE THREAD

**Issue by iamfakeguru** [seanpixel/Teenage-AGI#9]
I'm getting this error, it seems like a PINECONE problem.

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='controller.asia-southeast1-gc.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14970f490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

I've tried:
- making sure the .env file is correctly placed and named, by renaming the .env file with 'mv .env.template .env' in the terminal
- creating an index on pinecone (free plan)
- tried two different API keys (both are created with asia-southeast region by default, though that's not where I'm located)
- tried to run it in a docker container 'docker-compose run teenage-agi' (same error)
- the docker is running in the background
- all the required libraries are installed and updated

I'm out of ideas :/

**Comment by joshfryart** [comment]
Try deleting your index, and let the program create it itself. See if that
works.

**Comment by Philomath88** [comment]
I seem to have the same issue. I didn't have an index created. Here's the error log. 

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/maximiliandoelle/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "/Users/maximiliandoelle/Projects/openAPI/Teenage-AGI/main.py", line 14, in <module>
    agent.createIndex()
  File "/Users/maximiliandoelle/Projects/openAPI/Teenage-AGI/agent.py", line 96, in createIndex
    if self.table_name not in pinecone.list_indexes():
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api
    response_data = self.request(
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request
    return self.rest_client.GET(url,
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET
    return self.request("GET", url,
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request
    r = self.pool_manager.request(method, url,
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

**Comment by GitDakky** [comment]
Any news on this? I have exactly the same issue

**Comment by lalotrage** [comment]
Same issue here

> I seem to have the same issue. I didn't have an index created. Here's the error log.
> 
> [nltk_data] Downloading package punkt to [nltk_data] /Users/maximiliandoelle/nltk_data... [nltk_data] Package punkt is already up-to-date! Traceback (most recent call last): File "/Users/maximiliandoelle/Projects/openAPI/Teenage-AGI/main.py", line 14, in agent.createIndex() File "/Users/maximiliandoelle/Projects/openAPI/Teenage-AGI/agent.py", line 96, in createIndex if self.table_name not in pinecone.list_indexes(): File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/manage.py", line 185, in list_indexes response = api_instance.list_indexes() File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 776, in **call** return self.callable(self, *args, **kwargs) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api/index_operations_api.py", line 1132, in __list_indexes return self.call_with_http_info(**kwargs) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 838, in call_with_http_info return self.api_client.call_api( File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 413, in call_api return self.__call_api(resource_path, method, File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 200, in __call_api response_data = self.request( File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/api_client.py", line 439, in request return self.rest_client.GET(url, File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 236, in GET return self.request("GET", url, File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/pinecone/core/client/rest.py", line 202, in request r = self.pool_manager.request(method, url, File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/request.py", line 74, in request return self.request_encode_url( File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/request.py", line 96, in request_encode_url return self.urlopen(method, url, **extra_kw) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen response = conn.urlopen(method, u.request_uri, **kw) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1282, in request self._send_request(method, url, body, headers, encode_chunked) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1323, in _send_request self.putheader(hdr, value) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader _HTTPConnection.putheader(self, header, *values) File "/Users/maximiliandoelle/miniconda3/lib/python3.10/http/client.py", line 1259, in putheader if _is_illegal_header_value(values[i]): TypeError: expected string or bytes-like object
